#!/usr/bin/env python3
# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: Apache-2.0
"""Multi-algorithm checksum manifest for the vendored model GGUFs.

Gentoo-Manifest-style: one line per file, THREE independent hashes each
(MD5 + SHA-256 + BLAKE2b). Strength comes from agreement -- a file passes
only if EVERY algorithm matches. MD5 is a weak legacy extra kept per the
maintainer's Gentoo-style request; the real security is SHA-256 + BLAKE2b.

Line format (whitespace-separated, keyed by basename):
    DIST <basename> <size-bytes> MD5 <hex> SHA256 <hex> BLAKE2B <hex>

Stdlib only (hashlib) -- runs unchanged on the Linux client image and on the
macOS server, no huggingface_hub / venv needed.

Subcommands:
    write   MANIFEST FILE...   compute the 3 hashes for each FILE and upsert
                               its entry (other entries are preserved); the
                               manifest is rewritten sorted -> a reviewable diff.
    verify  MANIFEST FILE...   check each FILE against its manifest entry.
        --warn-unpinned        a FILE with no manifest entry (or no manifest
                               at all) is a WARNING, not a failure (used by the
                               pull gate for ad-hoc quants and by the serve gate
                               before the manifest is first generated).
        --quarantine           on a mismatch, rename the bad file aside to
                               <file>.corrupt so `make serve` can't load it.
    A mismatch of ANY algorithm on a PINNED file always fails loudly (exit 1).
"""
from __future__ import annotations

import hashlib
import os
import sys
from collections.abc import Callable
from typing import BinaryIO, Protocol, TextIO


class Hasher(Protocol):
    """The slice of a hashlib hash object this tool uses (one read pass, then a hex digest)."""

    def update(self, data: bytes, /) -> None: ...

    def hexdigest(self) -> str: ...


# A zero-argument constructor for a fresh hash object (hashlib.md5 / .sha256 / .blake2b all qualify).
HashConstructor = Callable[[], Hasher]

# Algorithm name (as written in the manifest) -> its hash constructor.
ALGOS: dict[str, HashConstructor] = {
    "MD5": hashlib.md5,
    "SHA256": hashlib.sha256,
    "BLAKE2B": hashlib.blake2b,
}
# The manifest writes hashes in this fixed order so a regenerated manifest diffs cleanly.
ALGO_ORDER: tuple[str, ...] = ("MD5", "SHA256", "BLAKE2B")
# 8 MiB read chunk; one disk pass feeds all three hashers (a GGUF is tens of GB, so hash once).
_READ_CHUNK: int = 8 * 1024 * 1024


def hash_file(path: str) -> tuple[int, dict[str, str]]:
    """Return (size_bytes, {ALGO: hexdigest}) computing all algos in ONE read pass."""
    hashers: dict[str, Hasher] = {name: ctor() for name, ctor in ALGOS.items()}
    size: int = 0
    handle: BinaryIO
    with open(path, "rb") as handle:
        while True:
            chunk: bytes = handle.read(_READ_CHUNK)
            if not chunk:
                break
            size += len(chunk)
            hasher: Hasher
            for hasher in hashers.values():
                hasher.update(chunk)
    return size, {name: hasher.hexdigest() for name, hasher in hashers.items()}


def load_manifest(manifest: str) -> dict[str, dict[str, str]]:
    """Parse MANIFEST into {basename: {'size': str, ALGO: hex, ...}}; {} if absent."""
    entries: dict[str, dict[str, str]] = {}
    if not os.path.exists(manifest):
        return entries
    handle: TextIO
    with open(manifest, encoding="utf-8") as handle:
        line: str
        for line in handle:
            fields: list[str] = line.split()
            if len(fields) < 3 or fields[0] != "DIST":
                continue
            name: str = fields[1]
            size: str = fields[2]
            record: dict[str, str] = {"size": size}
            rest: list[str] = fields[3:]
            i: int
            for i in range(0, len(rest) - 1, 2):
                record[rest[i].upper()] = rest[i + 1]
            entries[name] = record
    return entries


def format_entry(name: str, size: int, digests: dict[str, str]) -> str:
    """Render one Gentoo-style `DIST ...` manifest line (algorithms in ALGO_ORDER)."""
    ordered: str = " ".join(f"{algo} {digests[algo]}" for algo in ALGO_ORDER)
    return f"DIST {name} {size} {ordered}\n"


def write_manifest(manifest: str, entries: dict[str, dict[str, str]]) -> None:
    """Write ENTRIES to MANIFEST, one sorted `DIST` line per file, with a header comment."""
    handle: TextIO
    with open(manifest, "w", encoding="utf-8") as handle:
        handle.write("# Multi-hash manifest for the vendored model GGUFs "
                     "(MD5 + SHA-256 + BLAKE2b per file).\n")
        handle.write("# Generated by `make checksums-refresh`; a file passes "
                     "only if ALL three hashes match.\n")
        name: str
        for name in sorted(entries):
            record: dict[str, str] = entries[name]
            digests: dict[str, str] = {algo: record[algo] for algo in ALGOS}
            handle.write(format_entry(name, int(record["size"]), digests))


def cmd_write(manifest: str, files: list[str]) -> int:
    """Compute + upsert an entry for each FILE, preserving the rest; rewrite MANIFEST sorted."""
    entries: dict[str, dict[str, str]] = load_manifest(manifest)
    status: int = 0
    path: str
    for path in files:
        if not os.path.isfile(path):
            print(f"checksum: skip (not on disk): {path}", file=sys.stderr)
            continue
        name: str = os.path.basename(path)
        size: int
        digests: dict[str, str]
        size, digests = hash_file(path)
        entries[name] = {"size": str(size), **digests}
        print(f"checksum: pinned {name} ({size} bytes)")
    write_manifest(manifest, entries)
    return status


def cmd_verify(manifest: str, files: list[str], warn_unpinned: bool, quarantine: bool) -> int:
    """Verify each FILE against MANIFEST; return 1 if any pinned file mismatches or is missing."""
    entries: dict[str, dict[str, str]] = load_manifest(manifest)
    if not entries and warn_unpinned:
        print(f"checksum: WARNING no manifest at {manifest} yet -- cannot verify "
              f"({len(files)} file(s)); run `make checksums-refresh`.", file=sys.stderr)
        return 0
    status: int = 0
    path: str
    for path in files:
        name: str = os.path.basename(path)
        if not os.path.isfile(path):
            print(f"checksum: FAIL missing file: {path}", file=sys.stderr)
            status = 1
            continue
        record: dict[str, str] | None = entries.get(name)
        if record is None:
            msg: str = f"checksum: unpinned (no manifest entry): {name}"
            if warn_unpinned:
                print("checksum: WARNING " + msg, file=sys.stderr)
                continue
            print("checksum: FAIL " + msg, file=sys.stderr)
            status = 1
            continue
        size: int
        digests: dict[str, str]
        size, digests = hash_file(path)
        bad: list[str] = [algo for algo in ALGOS if digests[algo] != record.get(algo)]
        if str(size) != record.get("size"):
            bad.append("SIZE")
        if bad:
            status = 1
            print(f"\nchecksum MISMATCH: {name}", file=sys.stderr)
            print("  This file does NOT match its pinned checksum -- it may be "
                  "corrupted in transit or tampered upstream.", file=sys.stderr)
            print("  It will NOT be served.", file=sys.stderr)
            if "SIZE" in bad:
                print(f"    SIZE     expected {record.get('size')}  actual {size}",
                      file=sys.stderr)
            algo: str
            for algo in ALGO_ORDER:
                if algo in bad:
                    print(f"    {algo:<8} expected {record.get(algo)}  actual {digests[algo]}",
                          file=sys.stderr)
            if quarantine:
                aside: str = path + ".corrupt"
                try:
                    os.replace(path, aside)
                    print(f"  quarantined -> {aside} (moved aside so it can't be served)",
                          file=sys.stderr)
                except OSError as exc:
                    print(f"  could not quarantine {path}: {exc}", file=sys.stderr)
        else:
            print(f"checksum: OK {name} (MD5+SHA256+BLAKE2b)")
    return status


def main(argv: list[str]) -> int:
    """CLI entry: dispatch `write` / `verify`; return the process exit status."""
    if len(argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2
    cmd: str = argv[1]
    raw_args: list[str] = argv[2:]
    warn_unpinned: bool = "--warn-unpinned" in raw_args
    quarantine: bool = "--quarantine" in raw_args
    positional: list[str] = [arg for arg in raw_args if not arg.startswith("--")]
    manifest: str = positional[0]
    files: list[str] = positional[1:]
    if cmd == "write":
        return cmd_write(manifest, files)
    if cmd == "verify":
        return cmd_verify(manifest, files, warn_unpinned, quarantine)
    print(f"checksum: unknown subcommand {cmd!r}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
