#!/usr/bin/env bash
# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: Apache-2.0
#
# 01-install-base.sh -- install the full toolchain this sandbox image ships (~430
# Fedora packages: compilers/runtimes for a couple dozen languages, build tooling,
# debuggers/profilers, graphics dev libraries, the scientific-Python stack, databases,
# networking/security tools, editors).
#
# Extracted from the Dockerfile so the same package set can be installed on a bare Fedora
# host or a guest with no container runtime, not only during `podman build`. This image
# has a single, unconditional package group and no feature flags, so there is just this
# one script; the Dockerfile runs it. `dnf upgrade` stays in the Dockerfile (its own
# earlier layer, before the dotfiles COPY), so this script is purely `dnf install`.
#
# Add packages alphabetically (the list is intentionally maximal -- do not prune for
# "cleanliness"; it is a deliberately batteries-included dev box).
#
# Single dnf call, so its own exit status is this script's exit status.
set -uo pipefail

if ! command -v dnf >/dev/null 2>&1; then
    echo "01-install-base.sh: needs 'dnf' (this installs Fedora packages), not found." >&2
    echo "Run on a Fedora host/guest, or inside the project's Fedora-based image." >&2
    exit 1
fi

dnf install -y \
    alsa-lib-devel \
    ansible \
    ant \
    antlr4 \
    antlr4-cpp-runtime \
    antlr4-cpp-runtime-devel \
    aria2 \
    asciidoctor \
    asciinema \
    aspell \
    aspell-en \
    attr \
    audit-libs-devel \
    autoconf \
    automake \
    bash-completion \
    bat \
    bc \
    bear \
    bind-utils \
    binutils \
    binutils-devel \
    binutils-gold \
    bison \
    blas-devel \
    bmon \
    boost-devel \
    bpftrace \
    btop \
    buildah \
    bzip2 \
    bzip2-devel \
    cabal-install \
    ca-certificates \
    cairo-devel \
    cargo \
    ccache \
    clang \
    clang-analyzer \
    clang-devel \
    clang-tools-extra \
    clisp \
    cloc \
    clojure \
    cmake \
    colordiff \
    cppcheck \
    cronie \
    cscope \
    ctags \
    curl \
    dbus-devel \
    ddrescue \
    diffutils \
    direnv \
    distcc \
    dotnet-sdk-8.0 \
    doxygen \
    duf \
    eigen3-devel \
    elixir \
    emacs \
    emacs-gtk+x11 \
    emacs-pgtk \
    entr \
    erlang \
    ethtool \
    expat-devel \
    expect \
    eza \
    fakeroot \
    fd-find \
    fdupes \
    ffmpeg-free \
    fftw-devel \
    file \
    firewalld \
    fish \
    flex \
    fontconfig-devel \
    freeglut \
    freeglut-devel \
    freetype-devel \
    fuse-overlayfs \
    fzf \
    gawk \
    gcc \
    gcc-c++ \
    gdb \
    gettext \
    gettext-devel \
    gh \
    ghc \
    giflib-devel \
    git \
    git-lfs \
    glew-devel \
    glfw-devel \
    glib \
    glib2-devel \
    glibc-static \
    gmp-devel \
    gnupg2 \
    gnuplot \
    golang \
    google-perftools-devel \
    gopls \
    gource \
    gperf \
    graphviz \
    groff \
    gsl-devel \
    gtest-devel \
    gtk3-devel \
    gtk4-demo \
    gtk4-devel \
    gzip \
    heaptrack \
    htop \
    httpie \
    hyperfine \
    ImageMagick \
    inotify-tools \
    iotop \
    iperf3 \
    iproute \
    ipset \
    iptables \
    iputils \
    jansson-devel \
    java-25-openjdk \
    java-25-openjdk-devel \
    java-latest-openjdk-devel \
    jq \
    julia \
    kcachegrind \
    ksh \
    lapack-devel \
    latexmk \
    less \
    leveldb-devel \
    libacl-devel \
    libarchive-devel \
    libasan \
    libbsd-devel \
    libcap-devel \
    libcurl-devel \
    libcxx-devel \
    libdrm-devel \
    libedit-devel \
    libev-devel \
    libevent-devel \
    libffi-devel \
    libgcrypt-devel \
    libgit2-devel \
    libglvnd-gles \
    libheif-devel \
    libjpeg-turbo-devel \
    libnotify \
    libogg-devel \
    libpcap-devel \
    libpng-devel \
    librsvg2-devel \
    libseccomp-devel \
    libselinux-devel \
    libsodium-devel \
    libssh2-devel \
    libssh-devel \
    libstdc++-static \
    libtiff-devel \
    libtool \
    libubsan \
    libuuid-devel \
    libuv-devel \
    libvorbis-devel \
    libwebp-devel \
    libXcomposite \
    libxcrypt-devel \
    libXcursor \
    libXdamage \
    libXfixes \
    libXft \
    libXi \
    libXinerama \
    libxml2-devel \
    libXmu \
    libXrandr \
    libXrender \
    libXres \
    libXScrnSaver \
    libxslt-devel \
    libXtst \
    libXv \
    libXxf86vm \
    libyaml-devel \
    libzip-devel \
    libzip-tools \
    lld \
    lldb \
    lmdb-devel \
    lsb_release \
    lsof \
    ltrace \
    lua \
    lua-devel \
    luarocks \
    lz4 \
    lz4-devel \
    m4 \
    make \
    man-db \
    man-pages \
    mariadb \
    mariadb-devel \
    maven \
    memcached \
    mercurial \
    mesa-demos \
    mesa-dri-drivers \
    mesa-libEGL-devel \
    mesa-libGL-devel \
    meson \
    mingw64-gcc \
    mold \
    moreutils \
    mosh \
    mpfr-devel \
    mpv \
    mtr \
    myst-nb \
    nano \
    nasm \
    ncdu \
    ncurses-devel \
    neovim \
    nethogs \
    nettle-devel \
    net-tools \
    nginx \
    ninja-build \
    nlohmann-json-devel \
    nmap \
    nodejs \
    npm \
    nss-tools \
    ocaml \
    ocaml-cmdliner \
    ocaml-dune \
    octave \
    oniguruma-devel \
    opam \
    openblas-devel \
    openldap-devel \
    openssh-clients \
    openssl-devel \
    p7zip \
    PackageKit-gtk3-module \
    pandoc \
    pango-devel \
    parallel \
    patch \
    patchutils \
    pcre2-devel \
    perf \
    perl \
    perl-Image-ExifTool \
    php \
    php-cli \
    php-devel \
    pigz \
    pinentry \
    pipewire-devel \
    pkgconf-pkg-config \
    plocate \
    podman \
    polkit-devel \
    poppler-utils \
    postgresql \
    postgresql-devel \
    pre-commit \
    procps-ng \
    procs \
    progress \
    protobuf-compiler \
    pv \
    python3 \
    python3-black \
    python3-build \
    python3-clang \
    python3-cython \
    python3-devel \
    python3-furo \
    python3-ipython \
    python3-matplotlib \
    python3-mypy \
    python3-nanobind \
    python3-nbsphinx \
    python3-notebook \
    python3-numpy \
    python3-pandas \
    python3-pip \
    python3-pylint \
    python3-pytest \
    python3-pytest-xdist \
    python3-requests \
    python3-scikit-build-core \
    python3-scipy \
    python3-setuptools \
    python3-sphinx \
    python3-sympy \
    python3-tomli \
    python3-twisted \
    python3-virtualenv \
    python3-wheel \
    python3-yaml \
    qemu \
    qt5-qtbase-devel \
    qt6-qtbase-devel \
    qt6-qtbase-examples \
    R \
    racket \
    radare2 \
    ragel \
    rclone \
    R-core-devel \
    re2c \
    readline-devel \
    redhat-rpm-config \
    redis \
    ripgrep \
    rpm-build \
    rpmdevtools \
    rsync \
    ruby \
    ruby-devel \
    rubygems \
    ruff \
    rust \
    rust-analyzer \
    rustfmt \
    samba-client \
    sbcl \
    scons \
    SDL2_image-devel \
    SDL2_net-devel \
    SDL3-devel \
    SDL3_sound \
    SDL3_sound-devel \
    sed \
    ShellCheck \
    shfmt \
    skopeo \
    socat \
    sox \
    spdlog-devel \
    speedtest-cli \
    sqlite \
    sqlite-devel \
    strace \
    stress-ng \
    swift-lang \
    swig \
    sysbench \
    sysstat \
    systemd-devel \
    tcpdump \
    tesseract \
    texinfo \
    texlive \
    texlive-anyfontsize \
    texlive-capt-of \
    texlive-collection-fontsrecommended \
    texlive-collection-latexrecommended \
    texlive-dvipng \
    texlive-dvisvgm \
    texlive-eqparbox \
    texlive-fancyhdr \
    texlive-fncychap \
    texlive-fontspec \
    texlive-framed \
    texlive-gnu-freefont \
    texlive-luahbtex \
    texlive-lualatex-math \
    texlive-luatex85 \
    texlive-multirow \
    texlive-needspace \
    texlive-standalone \
    texlive-tabulary \
    texlive-threeparttable \
    texlive-titlesec \
    texlive-varwidth \
    texlive-wrapfig \
    the_silver_searcher \
    tig \
    tinyxml2-devel \
    tldr \
    tmate \
    tmux \
    tokei \
    traceroute \
    tree \
    ty \
    units \
    unzip \
    uv \
    valgrind \
    vim-enhanced \
    vulkan-tools \
    wabt \
    wayland-devel \
    wget \
    which \
    whois \
    wireguard-tools \
    wl-clipboard \
    xclip \
    xdg-desktop-portal-gtk \
    xdotool \
    xmlstarlet \
    xorg-x11-server-Xvfb \
    xz \
    xz-devel \
    yasm \
    yq \
    zenity \
    zig \
    zip \
    zlib-devel \
    zsh \
    zstd
